import Head from "next/head";
import Featured from "../components/Featured";
import PizzaList from "../components/PizzaList";
import styles from "../styles/Home.module.css";
import api from "../utils/api/api";

export default function Home({ pizzaList }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>PizzaMizza</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/" /> */}
      </Head>
      <Featured />
      <PizzaList pizzaList={pizzaList} />
    </div>
  );
}
export const getServerSideProps = async () => {
  const res = await api().get("/products");
  return {
    props: {
      pizzaList: res.data,
    },
  };
};
